---***1.- CREATE A QUERY THAT RETURNS THE LAST NAME OF THE EMPLOYEES THAT DOESN'T HAS EMPLOYEES IN THEIR ASSIGNMENT LIST,
---(NO MANAGERS)
SELECT E.LAST_NAME
FROM   EMPLOYEES E 
WHERE  E.EMPLOYEE_ID NOT IN(SELECT DISTINCT(MANAGER_ID) 
                            FROM   EMPLOYEES 
                            WHERE  MANAGER_ID IS NOT NULL); 
---Comprobation [We want NULL]
    SELECT *
    FROM   employees 
    WHERE  manager_id IN (SELECT E.EMPLOYEE_ID
                          FROM   EMPLOYEES E 
                          WHERE  E.EMPLOYEE_ID NOT IN(SELECT DISTINCT(MANAGER_ID) 
                                                      FROM   EMPLOYEES 
                                                      WHERE  MANAGER_ID IS NOT NULL));
                            
                            
---***2.- CREATE A QUERY THAT RETURN ALL DEPARTMENTS THAT HAS EMPLOYEES IN THER ASSIGNMENT LIST
SELECT DEPARTMENT_ID , DEPARTMENT_NAME 
FROM   DEPARTMENTS D
WHERE  EXISTS(SELECT 'OK' 
              FROM   EMPLOYEES 
              WHERE  DEPARTMENT_ID = D.DEPARTMENT_ID)
ORDER BY 1 DESC;                

---***3.- CREATE A QUERY THAT GETS ALL DEPARTMENTS THAT DOESN'T HAS EMPLOYEES IN THEIR ASSIGNMENT LIST
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM   DEPARTMENTS D
WHERE  NOT EXISTS(SELECT 'OK' 
                  FROM   EMPLOYEES 
                  WHERE  DEPARTMENT_ID = D.DEPARTMENT_ID);              

---***4.- CREATE A QUERY THAT RETURNS **ALL** DEPARTMENTS [ID, NAME] THAT DOESN'T HAS EMPLOYEES IN THEIR ASSIGNMENT LIST               

---FORM 1 ;)
SELECT     DISTINCT(D.DEPARTMENT_ID), D.DEPARTMENT_NAME 
FROM       EMPLOYEES E 
RIGHT JOIN DEPARTMENTS D
ON         (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
WHERE      E.DEPARTMENT_ID IS NULL
ORDER BY   1 DESC;
---FORM 2  ;)
SELECT DISTINCT(D.DEPARTMENT_ID), D.DEPARTMENT_NAME 
FROM   EMPLOYEES E, DEPARTMENTS D
WHERE  E.DEPARTMENT_ID(+) = D.DEPARTMENT_ID
AND    E.DEPARTMENT_ID IS NULL
ORDER  BY 1 DESC;
---FORM 3  ;)
SELECT DEPARTMENT_ID, DEPARTMENT_NAME 
FROM   DEPARTMENTS
WHERE  DEPARTMENT_ID NOT IN(SELECT DEPARTMENT_ID 
                            FROM EMPLOYEES 
                            WHERE DEPARTMENT_ID IS NOT NULL);
---***5.- CREATE A QUERY THAT RETURNS THE DEPARTMENTS [ID, NAME] THAT APPEARS ON THE EMPLOYEES LIST
---FORM 1  ;)
SELECT DEPARTMENT_ID, DEPARTMENT_NAME 
FROM   DEPARTMENTS D
WHERE  DEPARTMENT_ID IN (SELECT DEPARTMENT_ID 
                         FROM   EMPLOYEES 
                         WHERE  DEPARTMENT_ID IS NOT NULL);
---FORM 2  ;)
SELECT DEPARTMENT_ID, DEPARTMENT_NAME 
FROM   DEPARTMENTS D
WHERE  EXISTS (SELECT '1' 
               FROM EMPLOYEES 
               WHERE D.DEPARTMENT_ID = DEPARTMENT_ID);
---FORM 3  ;)
SELECT  DEPARTMENT_ID, DEPARTMENT_NAME
FROM    DEPARTMENTS
INTERSECT
SELECT  DISTINCT(DEPARTMENT_ID), (SELECT DEPARTMENT_NAME 
                                  FROM   DEPARTMENTS
                                  WHERE  DEPARTMENT_ID = E.DEPARTMENT_ID) NAME
FROM    EMPLOYEES E
WHERE   DEPARTMENT_ID IS NOT NULL;

---Created and Revised by I.S.C.H. Jesús José Navarrete Baca @ChecheSwap
 
 
 
                    
                
